name: Deploy Portfolio Website to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: hello 
        run: echo "hello from github actions"
       

      - name: rep name
        run: echo "this workflow is running in ${{github.respository}}"