name: Deploy Portfolio Website to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync ./website s3://waseem-portfolio-website-bucket \
            --delete \
            --acl public-read

      - name: Notify completion
        run: echo "✅ Deployment completed successfully!"
